CREATE OR REPLACE VIEW public.participant_attendance
AS SELECT p.id AS sys_participant_id,
    p.application_id,
    concat(p.firstname, ' ', p.lastname) AS participant_name,
    p.middlename,
    p.gender,
    2021 - "left"(p.birthdate::text, 4)::integer AS participant_age_est,
    p.type,
    p.status,
    p.total_income,
    p.total_poverty_score,
    p.selection_score,
    p.has_score_card,
    p.is_visitor,
    p.is_non_icm_participant,
    p.deleted_at,
    p.created_at,
    p.updated_at,
    p.is_non_sg,
    p.is_kid_saver,
    p.sg_role,
    p.old_id,
    pa.id AS sys_partattend_id,
    pa.participant_id,
    pa.community_id,
    pa.h2h_week1,
    pa.h2h_week2,
    pa.h2h_week3,
    pa.h2h_week4,
    pa.week1,
    pa.week2,
    pa.week3,
    pa.week4,
    pa.week5,
    pa.week6,
    pa.week7,
    pa.week8,
    pa.week9,
    pa.week10,
    pa.week11,
    pa.week12,
    pa.week13,
    pa.week14,
    pa.week15,
    pa.week16,
    pa.graduate,
    pa.garden_week1,
    pa.garden_week14
   FROM participants p
     LEFT JOIN participant_attendances pa ON p.id = pa.participant_id;