CREATE OR REPLACE VIEW public.prevail_report
AS SELECT cs.community_id,
    cs.fy_batch,
    cs.sg_stream,
    cs.base_name,
    cs.branch_name,
    cs.old_community_id,
    cs.savings_group_id,
    cs.pastor_name,
    cs.pastor_id,
    cs.sg_name,
    cs.sg_deleted,
    cs.cluster_id,
    cs.sg_created_at,
    cs.application_id,
    cs.community_city,
    cs.community_barangay,
    cs.community_street,
    cs.program_id,
    cs.applied_at,
    cs.approved,
    sgd.id AS prevail_report_id,
    sgd.report_at AS prevail_report_date,
    sgd.attended AS prevail_attendance,
    sgd.total_contributions AS report_contributions,
    sgd.total_withdrawn AS report_withdrawn,
    sgd.balance AS report_balance,
    sgd.total_loans_released AS report_loans_released,
    sgd.total_loans_released AS report_loans_repayments,
    sgd.total_social_fund_payout AS report_sf_payout,
    sgd.total_capital_for_business AS report_business_capital,
    sgd.gross_sale AS report_gross_sale,
    sgd.created_at AS report_created_at,
    sgd.updated_at AS report_updated_at,
    sgd.total_icm_participants AS report_icm_part,
    sgd.total_non_icm_participants AS report_nonicm_part,
    sgd.total_participants AS report_part,
    sgd.total_kid_saver_participants AS report_kid_savers
   FROM savings_group_data sgd
     LEFT JOIN community_sg cs ON cs.savings_group_id = sgd.savings_group_id
     LEFT JOIN savings_groups sg ON sgd.savings_group_id = sg.id
  WHERE cs.savings_group_id IS NOT NULL;
